services:
  mlflow_server:
    build:
      context: ./mlflow_server
    image: razansid786/cheating-detection-mlflow:v1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow_server/mlruns
      - ./mlflow_server/models:/mlflow_server/models:ro  
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  flask_web:
    build:
      context: ./flask_web
    image: razansid786/cheating-detection-web:v1
    container_name: flask_web
    ports:
      - "5001:5001"
    volumes:
      - ./flask_web/uploads:/app/uploads
      - ./flask_web/TEMP_output:/app/TEMP_output
      - ./flask_web/summary:/app/summary
      - ./flask_web/static:/app/static
      - ./flask_web/models_cache:/app/models_cache
      - mlflow_data:/mlflow_server/mlruns 
      - ./mlflow_server/models:/mlflow_server/models:ro  

    depends_on:
      mlflow_server:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  mlflow-artifacts:
  mlflow_data:
  uploads_data:
  temp_output_data:
  summary_data:
  static_data: