FROM ultralytics/ultralytics:latest

WORKDIR /mlflow_server

RUN pip install --upgrade pip

RUN pip install --timeout=1000 --retries=5 \
    --index-url https://mirrors.aliyun.com/pypi/simple/ \
    --extra-index-url https://pypi.org/simple \
    --trusted-host mirrors.aliyun.com \
    mlflow==2.9.2 dvc dvc-s3

COPY server.py .
COPY entrypoint.sh .
COPY models/ models/

RUN chmod +x entrypoint.sh

RUN mkdir -p /mlflow_server/mlruns

EXPOSE 5000

CMD ["./entrypoint.sh"]
