# # Use PyTorch base image with Python 3.11
# # This already includes PyTorch, so you don't need to download it
# FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

# WORKDIR /app

# # Install system dependencies that OpenCV needs
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     libglib2.0-0 \
#     libgomp1 \
#     libgl1 \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# # Copy requirements first
# COPY requirements.txt .

# # Remove torch from requirements.txt and install remaining packages
# # Using cache mount for faster rebuilds
# RUN --mount=type=cache,target=/root/.cache/pip \
#     grep -v "^torch" requirements.txt > requirements_filtered.txt && \
#     pip install --no-cache-dir -r requirements_filtered.txt

# # Copy application files
# COPY templates/ templates/
# COPY tempapp.py .

# # Create necessary directories
# RUN mkdir -p temp_output uploads summary static/outputs

# EXPOSE 8000

# CMD ["python", "tempapp.py"]

# FROM python:3.10

# WORKDIR /app

# # Install system dependencies for OpenCV
# # RUN apt-get update && apt-get install -y \
# #     libgl1-mesa-glx \
# #     libglib2.0-0 \
# #     libsm6 \
# #     libxext6 \
# #     libxrender-dev \
# #     libgomp1 \
# #     && rm -rf /var/lib/apt/lists/*

# # Copy requirements and install
# COPY requirements.txt .
# RUN pip install -r requirements.txt

# # Copy application files
# COPY app.py .

# # Create necessary folders
# RUN mkdir -p uploads temp_output summary static/outputs

# EXPOSE 5000

# CMD ["python", "app.py"]


FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libglib2.0-dev \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir --timeout=1000 --retries=5 \
    --index-url https://mirrors.aliyun.com/pypi/simple/ \
    --trusted-host mirrors.aliyun.com \
    -r requirements.txt
COPY . .

CMD ["python", "app.py"]