FROM python:3.11
WORKDIR /app

COPY requirements.txt .
COPY templates/ templates/
COPY tempapp.py .

RUN pip install -r requirements.txt

RUN mkdir -p temp_output uploads summary static/outputs

EXPOSE 8000

CMD ["python", "tempapp.py"]
